apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flomesh-gui
  name: flomesh-gui
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: flomesh-gui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flomesh-gui
    spec:
      containers:
      - env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_NAME
          value: flomesh
        - name: DATABASE_PASSWORD
          value:  Flomesh.123
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_TYPE
          value: postgres
        - name: DATABASE_USERNAME
          value: flomesh
        - name: HOST
          value: '::'
        - name: PIPY_REPO_HOST
          value: pipy-repo
        - name: PIPY_REPO_PORT
          value: "6060"
        - name: PORT
          value: "8080"
        - name: TZ
          value: Asia/Shanghai
        image: flomesh-gui-alpine:2.0.0-199
        imagePullPolicy: IfNotPresent
        name: flomesh-gui
        ports:
        - containerPort: 8080
          name: flomesh-gui-web
          protocol: TCP
        securityContext:
          capabilities: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: flomesh
spec:
  selector:
    app: flomesh-gui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
      name: flomesh-gui
  type: NodePort
