apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pipy-repo
  name: pipy-repo
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: pipy-repo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: pipy-repo
    spec:
      containers:
      - args:
        - pipy
        env:
        - name: PIPY_INSTANCE_NAME
          value: pipy-repo-ch
        - name: TZ
          value: Asia/Shanghai
        image: flomesh/pipy-repo-nightly:latest
        imagePullPolicy: IfNotPresent
        name: pipy-repo
        ports:
        - containerPort: 6060
          name: pipy-repo
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: pipy-repo
spec:
  selector:
    app: pipy-repo
  ports:
    - protocol: TCP
      port: 6060
      targetPort: 6060
      nodePort: 30060
      name: pipy-repo
  type: NodePort
